"""
Test Empty Credentials Validation
Generated by Enhanced AutoGen Test Creation Agent
Page Object Pattern Test - Uses page object models
"""

import pytest
import logging
from datetime import datetime
from pages.login_page import LoginPage
from pages.dashboard_page import DashboardPage

class TestEmptyCredentialsValidation:
    """Test class for Empty Credentials Validation"""
    
    def test_empty_credentials_validation(self, browser_setup):
        """
        Test: Empty Credentials Validation
        Description: Test login with empty credentials and verify validation messages
        """
        page, browser, context = browser_setup
        
        # Test data from requirements.json
        test_data = {'valid_username': 'Admin', 'valid_password': 'admin123', 'invalid_username': 'InvalidUser', 'invalid_password': 'WrongPassword123', 'base_url': 'https://opensource-demo.orangehrmlive.com', 'empty_username': '', 'empty_password': ''}
        
        try:
            # Get application URL
            app_url = test_data.get("base_url")
            if not app_url:
                raise ValueError("No application URL provided. Please specify base_url in test data.")
            
            # Initialize page objects
            login_page = LoginPage(page)
            dashboard_page = DashboardPage(page)
            # Step 1: Navigate to login page
            login_page.navigate()
            logging.info("Navigation step completed")
            # Step 2: Leave username empty
            # Generic step using page object: Leave username empty
            logging.info("Executing step: Leave username empty")
            page.wait_for_timeout(500)
            # Step 3: Leave password empty
            # Generic step using page object: Leave password empty
            logging.info("Executing step: Leave password empty")
            page.wait_for_timeout(500)
            # Step 4: Click login button
            # Click login button using page object
            success = login_page.click_element("login_button")
            if not success:
                raise AssertionError("Could not find or click login button using page object")
            page.wait_for_load_state("networkidle")

            # Validations using page objects
            # Verify error message using page object
            # Wait for error message to appear
            page.wait_for_timeout(2000)
            error_found = False
            
            # Try login page first (error messages typically appear on login page)
            try:
                is_visible = login_page.is_element_visible("error_message")
                if is_visible:
                    error_found = True
                    logging.info("Error message validation passed using login_page")
                else:
                    logging.debug("Error message not visible on login_page")
            except Exception as e:
                logging.debug(f"Failed to find error_message on login_page: {e}")
            
            # Fallback to dashboard page if not found on login page
            if not error_found:
                try:
                    is_visible = dashboard_page.is_element_visible("error_message")
                    if is_visible:
                        error_found = True
                        logging.info("Error message validation passed using dashboard_page")
                    else:
                        logging.debug("Error message not visible on dashboard_page")
                except Exception as e:
                    logging.debug(f"Failed to find error_message on dashboard_page: {e}")
            
            # Final assertion with more informative error message
            if not error_found:
                logging.error("Error message not found on any page - this might indicate the application doesn't show error messages as expected")
            assert error_found, "Error message not displayed on any page"
            
            # Verify error message using page object
            # Wait for error message to appear
            page.wait_for_timeout(2000)
            error_found = False
            
            # Try login page first (error messages typically appear on login page)
            try:
                is_visible = login_page.is_element_visible("error_message")
                if is_visible:
                    error_found = True
                    logging.info("Error message validation passed using login_page")
                else:
                    logging.debug("Error message not visible on login_page")
            except Exception as e:
                logging.debug(f"Failed to find error_message on login_page: {e}")
            
            # Fallback to dashboard page if not found on login page
            if not error_found:
                try:
                    is_visible = dashboard_page.is_element_visible("error_message")
                    if is_visible:
                        error_found = True
                        logging.info("Error message validation passed using dashboard_page")
                    else:
                        logging.debug("Error message not visible on dashboard_page")
                except Exception as e:
                    logging.debug(f"Failed to find error_message on dashboard_page: {e}")
            
            # Final assertion with more informative error message
            if not error_found:
                logging.error("Error message not found on any page - this might indicate the application doesn't show error messages as expected")
            assert error_found, "Error message not displayed on any page"
            
            # Generic validation: Verify URL contains '/login'
            logging.info("Validation: Verify URL contains '/login'")
            

            # Final verification
            page.wait_for_timeout(1000)  # Allow UI to settle
            
            logging.info(f"Test empty_credentials_validation completed successfully")
            
        except Exception as e:
            logging.error(f"Test empty_credentials_validation failed: {str(e)}")
            raise
