"""
Test Valid Login with Comprehensive Validations
Generated by Enhanced AutoGen Test Creation Agent
"""

import pytest
import logging
from datetime import datetime
from pages.login_page import LoginPage
from utils.locator_strategy import LocatorStrategy

class TestValidLoginWithComprehensiveValidations:
    """Test class for Valid Login with Comprehensive Validations"""
    
    def test_valid_login_with_comprehensive_validations(self, browser_setup):
        """
        Test: Valid Login with Comprehensive Validations
        Description: Test login with valid credentials and verify all expected elements
        """
        page, browser, context = browser_setup
        
        # Test data from requirements.json
        test_data = {'valid_username': 'Admin', 'valid_password': 'admin123', 'invalid_username': 'InvalidUser', 'invalid_password': 'WrongPassword123', 'base_url': 'https://opensource-demo.orangehrmlive.com'}
        
        # Initialize locator strategy for robust element finding
        locator_strategy = LocatorStrategy(page)
        
        try:
            # Initialize page object
            page_obj = LoginPage(page)
            
            # Navigate to application
            page.goto("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
            page.wait_for_load_state("networkidle")
            
            # Execute test steps with discovered selectors
            # Step 1: Navigate to login page
            # Navigate using page object
            page_obj.navigate()
            # Step 2: Enter valid username
            # Enter username using test data
            page_obj.fill_username(test_data.get("valid_username", "Admin"))
            page.wait_for_timeout(200)
            # Step 3: Enter valid password
            # Enter password using test data
            page_obj.fill_password(test_data.get("valid_password", "admin123"))
            page.wait_for_timeout(200)
            # Step 4: Click login button
            # Click login button using page object
            page_obj.click_login()
            page.wait_for_timeout(500)

            # Specific validations from requirements.json using LocatorStrategy
            assert "/dashboard" in page.url, "URL should contain '/dashboard'"
            assert locator_strategy.is_visible("user_display"), "User name should be displayed"
            assert locator_strategy.is_visible("logout_button"), "Logout option should be available"
            assert locator_strategy.is_visible("dashboard_content"), "Dashboard should be displayed"

            # Expected result validation: User should be logged in and redirected to dashboard with all navigation elements visible
            assert page.url is not None, "Expected result should be achieved"

            # Final verification
            page.wait_for_timeout(1000)  # Allow UI to settle
            
            logging.info(f"Test valid_login_with_comprehensive_validations completed successfully")
            
        except Exception as e:
            logging.error(f"Test valid_login_with_comprehensive_validations failed: {str(e)}")
            raise
