"""
Test Logout
Generated by Enhanced AutoGen Test Creation Agent
"""

import pytest
import logging
from datetime import datetime
from pages.main_page import MainPage

class TestLogout:
    """Test class for Logout"""
    
    def test_logout(self, browser_setup):
        """
        Test: Logout
        Description: Test logout functionality
        """
        page, browser, context = browser_setup
        
        try:
            # Initialize page object
            page_obj = MainPage(page)
            
            # Navigate to application
            page.goto("https://demo.automationexercise.com")
            page.wait_for_load_state("networkidle")
            
            # Execute test steps with discovered selectors
            # Step 1: Login with valid credentials
            # Perform complete login using page object
            page_obj.login("Admin", "admin123")
            page.wait_for_timeout(1000)
            # Step 2: Click on user dropdown
            # Generic step: Click on user dropdown
            page.wait_for_timeout(500)
            logging.info("Executed step: Click on user dropdown")
            # Step 3: Click logout
            # Generic step: Click logout
            page.wait_for_timeout(500)
            logging.info("Executed step: Click logout")
            # Step 4: Verify redirect to login page
            # Verification step 4
            # Wait for expected element to be visible
            page.wait_for_selector("body", timeout=5000)
            
            # Assert the step was successful
            assert page.url is not None, "Page should be loaded"

            # Final verification
            page.wait_for_timeout(1000)  # Allow UI to settle
            
            logging.info(f"Test logout completed successfully")
            
        except Exception as e:
            logging.error(f"Test logout failed: {str(e)}")
            raise
