"""
Test product search functionality
Generated by Enhanced AutoGen Test Creation Agent
"""

import pytest
from playwright.async_api import async_playwright, Page, Browser, BrowserContext
import asyncio
import logging
from datetime import datetime

class TestProductSearchTest:
    """Test class for product_search_test"""
    
    @pytest.fixture(scope="class")
    async def browser_setup(self):
        """Setup browser for tests"""
        playwright = await async_playwright().start()
        browser = await playwright.chromium.launch(headless=True)
        context = await browser.new_context()
        page = await context.new_page()
        
        yield page, browser, context, playwright
        
        await context.close()
        await browser.close()
        await playwright.stop()
    
    @pytest.mark.asyncio
    async def test_product_search_test(self, browser_setup):
        """
        Test: product_search_test
        Description: Test product search functionality
        """
        page, browser, context, playwright = browser_setup
        
        try:
            # Navigate to application
            await page.goto("https://advantageonlineshopping.com")
            await page.wait_for_load_state("networkidle")
            
            # Execute test steps with real selectors
            # Step 1: Navigate to home page
            await page.goto(page.url)  # Already navigated in setup
            # Step 2: Enter search term in search box
            # Perform search
            await page.fill("#searchBox", "laptop")
            await page.press("#searchBox", "Enter")
            await page.wait_for_timeout(1000)
            # Step 3: Click search button
            # Perform search
            await page.fill("#searchBox", "laptop")
            await page.press("#searchBox", "Enter")
            await page.wait_for_timeout(1000)
            # Step 4: Verify search results displayed
            # Perform search
            await page.fill("#searchBox", "laptop")
            await page.press("#searchBox", "Enter")
            await page.wait_for_timeout(1000)

            # Final verification
            await page.wait_for_timeout(1000)  # Allow UI to settle
            
            # Take screenshot for evidence
            await page.screenshot(path=f"test_evidence_{test_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png")
            
            logging.info(f"Test {test_name} completed successfully")
            
        except Exception as e:
            # Take screenshot on failure
            await page.screenshot(path=f"test_failure_{test_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png")
            logging.error(f"Test {test_name} failed: {str(e)}")
            raise
