"""
Login Page Object
Generated by Enhanced AutoGen Test Creation Agent
"""

from playwright.sync_api import Page
import logging

class LoginPage:
    """Page object for Login"""
    
    def __init__(self, page: Page):
        self.page = page
        self.url = "https://demo.testfire.net"
        
        # Element selectors discovered from application analysis
        self.username_field = "input[name='username']"
        self.password_field = "input[name='password']"
        self.login_button = "button[type='submit']"
        
    def navigate(self):
        """Navigate to Login"""
        self.page.goto(self.url)
        self.page.wait_for_load_state("networkidle")
        
    def fill_username(self, username: str):
        """Fill username field"""
        self.page.fill(self.username_field, username)
        
    def fill_password(self, password: str):
        """Fill password field"""
        self.page.fill(self.password_field, password)
        
    def click_login(self):
        """Click login button"""
        self.page.click(self.login_button)
        
    def login(self, username: str, password: str):
        """Perform complete login"""
        self.fill_username(username)
        self.fill_password(password)
        self.click_login()
