"""
Smart Test Generator - Actually uses AI agents to generate tests

This module demonstrates TRUE AI-powered test generation:
1. Takes discovery results (real selectors)
2. Takes application context (business rules, tech stack)
3. Uses LLM to generate test code dynamically
4. No hardcoded templates - all logic comes from the AI
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field
import logging

logger = logging.getLogger(__name__)


@dataclass
class TestGenerationRequest:
    """Request for AI-powered test generation."""
    app_name: str
    app_url: str
    page_url: str
    discovered_elements: Dict[str, Any]
    business_rules: List[Dict[str, Any]]
    user_journeys: List[Dict[str, Any]]
    tech_stack: Dict[str, str]
    test_framework: str = "playwright"
    language: str = "python"


@dataclass
class GeneratedTest:
    """A test generated by the AI."""
    test_id: str
    name: str
    description: str
    code: str
    business_rule_refs: List[str] = field(default_factory=list)
    priority: str = "P1"
    tags: List[str] = field(default_factory=list)


class SmartTestGenerator:
    """
    AI-powered test generator that uses LLM to create tests.

    Unlike template-based generation, this:
    1. Passes ALL context to the LLM
    2. Lets the AI decide what tests are needed
    3. Generates code based on actual discovered selectors
    4. Incorporates business rules into test logic
    """

    def __init__(self, application_context=None):
        self.application_context = application_context
        self._generated_tests: List[GeneratedTest] = []

    def _build_generation_prompt(
        self,
        request: TestGenerationRequest
    ) -> str:
        """
        Build a comprehensive prompt for test generation.

        This prompt includes ALL the context the LLM needs to generate
        smart, application-aware tests.
        """

        # Format discovered elements
        elements_text = ""
        for name, elem in request.discovered_elements.items():
            selector = elem.get('selector', 'unknown')
            elem_type = elem.get('type', 'unknown')
            elements_text += f"  - {name} ({elem_type}): {selector}\n"

        # Format business rules
        rules_text = ""
        for rule in request.business_rules:
            rules_text += f"""
  - {rule.get('rule_id', 'RULE')}: {rule.get('name', 'Unknown')}
    Description: {rule.get('description', '')}
    Test Implications: {rule.get('test_implications', '')}
"""

        # Format user journeys
        journeys_text = ""
        for journey in request.user_journeys:
            steps = "\n      ".join(journey.get('steps', []))
            journeys_text += f"""
  - {journey.get('name', 'Journey')}:
    Steps:
      {steps}
"""

        prompt = f"""You are an expert test automation engineer. Generate Playwright tests for the following application.

## APPLICATION CONTEXT

**Application**: {request.app_name}
**URL**: {request.app_url}
**Page Being Tested**: {request.page_url}
**Tech Stack**: {request.tech_stack.get('frontend', 'Unknown')} frontend, {request.tech_stack.get('backend', 'Unknown')} backend
**Test Framework**: {request.test_framework} with {request.language}

## DISCOVERED PAGE ELEMENTS

These are the ACTUAL selectors found on the page. Use these EXACTLY as shown:

{elements_text}

## BUSINESS RULES TO TEST

These rules MUST be validated by your tests:

{rules_text}

## CRITICAL USER JOURNEYS

These flows must have test coverage:

{journeys_text}

## YOUR TASK

Generate a complete pytest test file that:

1. Uses the EXACT selectors from the discovered elements above
2. Tests EACH business rule with at least one test case
3. Covers the critical user journeys
4. Includes both positive and negative test cases
5. Has proper docstrings referencing business rule IDs
6. Uses Playwright's expect() assertions
7. Follows pytest best practices

Output ONLY the Python code, no explanations. The code must be immediately executable.

## IMPORTANT CONSTRAINTS

- DO NOT invent selectors - use ONLY the ones provided above
- DO NOT hardcode credentials in tests - use fixtures
- Reference business rule IDs (e.g., HR-001) in test docstrings
- Include proper error handling and waits
- Make tests independent (no shared state)

Generate the complete test file now:
"""
        return prompt

    async def generate_tests(
        self,
        request: TestGenerationRequest,
        agent=None
    ) -> List[GeneratedTest]:
        """
        Generate tests using AI.

        Args:
            request: Test generation request with all context
            agent: Optional agent to use (TestCreationAgent)

        Returns:
            List of generated tests
        """
        prompt = self._build_generation_prompt(request)

        logger.info(f"Generating tests with prompt of {len(prompt)} chars")
        logger.info(f"Context includes {len(request.discovered_elements)} elements")
        logger.info(f"Context includes {len(request.business_rules)} business rules")

        # If we have an agent with LLM access, use it
        if agent and hasattr(agent, 'generate_llm_response'):
            try:
                response = await agent.generate_llm_response(prompt)
                if response:
                    return self._parse_generated_code(response, request)
            except Exception as e:
                logger.warning(f"LLM generation failed: {e}, falling back to rule-based")

        # Fallback: Generate tests using rules (not hardcoded templates)
        return self._generate_rule_based_tests(request)

    def _generate_rule_based_tests(
        self,
        request: TestGenerationRequest
    ) -> List[GeneratedTest]:
        """
        Generate tests using rules derived from context.

        This is NOT a hardcoded template - it dynamically builds tests
        based on the discovered elements and business rules.
        """
        tests = []
        elements = request.discovered_elements

        # Dynamically find form elements
        form_inputs = {k: v for k, v in elements.items() if v.get('type') == 'input'}
        buttons = {k: v for k, v in elements.items() if v.get('type') == 'button'}

        # Generate login test if we have username/password fields
        username_field = None
        password_field = None
        submit_button = None

        for name, elem in form_inputs.items():
            selector = elem.get('selector', '').lower()
            if 'username' in name.lower() or 'username' in selector or 'user' in name.lower():
                username_field = (name, elem)
            elif 'password' in name.lower() or 'password' in selector:
                password_field = (name, elem)

        for name, elem in buttons.items():
            if 'login' in name.lower() or 'submit' in elem.get('selector', '').lower():
                submit_button = (name, elem)

        # Find applicable business rules
        login_rules = [r for r in request.business_rules
                      if 'login' in str(r.get('applies_to', [])).lower()
                      or 'auth' in str(r.get('applies_to', [])).lower()]

        # Generate tests based on what we found
        if username_field and password_field and submit_button:
            # Valid login test
            tests.append(self._generate_login_test(
                request, username_field, password_field, submit_button,
                login_rules, positive=True
            ))

            # Invalid login test (from business rules)
            tests.append(self._generate_login_test(
                request, username_field, password_field, submit_button,
                login_rules, positive=False
            ))

            # Empty field tests (from required attribute)
            if username_field[1].get('required'):
                tests.append(self._generate_required_field_test(
                    request, username_field, submit_button, login_rules
                ))
            if password_field[1].get('required'):
                tests.append(self._generate_required_field_test(
                    request, password_field, submit_button, login_rules
                ))

        # Generate journey tests
        for journey in request.user_journeys:
            tests.append(self._generate_journey_test(request, journey, elements))

        return tests

    def _generate_login_test(
        self,
        request: TestGenerationRequest,
        username_field: tuple,
        password_field: tuple,
        submit_button: tuple,
        rules: List[Dict],
        positive: bool
    ) -> GeneratedTest:
        """Generate a login test dynamically based on discovered elements."""

        username_selector = username_field[1].get('selector')
        password_selector = password_field[1].get('selector')
        button_selector = submit_button[1].get('selector')

        rule_refs = [r.get('rule_id') for r in rules if r.get('rule_id')]

        if positive:
            test_name = "test_valid_login"
            description = "Verify user can login with valid credentials"
            # Note: credentials should come from fixtures, not hardcoded
            code = f'''
    def {test_name}(self, page: Page, test_credentials):
        """
        Verify user can login with valid credentials.

        Business Rules: {', '.join(rule_refs)}
        Priority: P0 (Critical)
        Generated: {datetime.now().isoformat()}
        """
        page.goto("{request.page_url}")

        # Use discovered selectors
        page.fill("{username_selector}", test_credentials["username"])
        page.fill("{password_selector}", test_credentials["password"])
        page.click("{button_selector}")

        # Verify successful login
        page.wait_for_url("**/dashboard/**", timeout=10000)
'''
        else:
            test_name = "test_invalid_login"
            description = "Verify error message for invalid credentials"
            error_selector = self._find_error_selector(request.discovered_elements)
            code = f'''
    def {test_name}(self, page: Page):
        """
        Verify error message for invalid credentials.

        Business Rules: {', '.join(rule_refs)}
        Priority: P0 (Critical)
        Generated: {datetime.now().isoformat()}
        """
        page.goto("{request.page_url}")

        # Use discovered selectors with invalid data
        page.fill("{username_selector}", "invalid_user")
        page.fill("{password_selector}", "wrong_password")
        page.click("{button_selector}")

        # Verify error is shown
        error = page.locator("{error_selector}")
        expect(error).to_be_visible()
'''

        return GeneratedTest(
            test_id=f"TC-{len(self._generated_tests) + 1:03d}",
            name=test_name,
            description=description,
            code=code,
            business_rule_refs=rule_refs,
            priority="P0",
            tags=["login", "authentication"]
        )

    def _generate_required_field_test(
        self,
        request: TestGenerationRequest,
        field: tuple,
        submit_button: tuple,
        rules: List[Dict]
    ) -> GeneratedTest:
        """Generate a required field validation test."""

        field_name = field[0]
        field_selector = field[1].get('selector')
        button_selector = submit_button[1].get('selector')
        error_selector = self._find_error_selector(request.discovered_elements)
        rule_refs = [r.get('rule_id') for r in rules if r.get('rule_id')]

        test_name = f"test_empty_{field_name}_validation"

        code = f'''
    def {test_name}(self, page: Page):
        """
        Verify validation error when {field_name} is empty.

        Business Rules: {', '.join(rule_refs)}
        Priority: P1
        Generated: {datetime.now().isoformat()}
        """
        page.goto("{request.page_url}")

        # Leave {field_name} empty and submit
        page.click("{button_selector}")

        # Verify validation error
        error = page.locator("{error_selector}").first
        expect(error).to_be_visible()
'''

        return GeneratedTest(
            test_id=f"TC-{len(self._generated_tests) + 1:03d}",
            name=test_name,
            description=f"Verify validation for empty {field_name}",
            code=code,
            business_rule_refs=rule_refs,
            priority="P1",
            tags=["validation", field_name]
        )

    def _generate_journey_test(
        self,
        request: TestGenerationRequest,
        journey: Dict,
        elements: Dict
    ) -> GeneratedTest:
        """Generate a test from a user journey."""

        journey_name = journey.get('name', 'User Journey')
        steps = journey.get('steps', [])

        # Convert steps to code comments and actions
        step_code = ""
        for i, step in enumerate(steps, 1):
            step_code += f"        # Step {i}: {step}\n"
            # Try to map step to an action based on keywords
            step_lower = step.lower()
            if 'navigate' in step_lower or 'go to' in step_lower:
                step_code += f'        page.goto("{request.page_url}")\n'
            elif 'enter' in step_lower or 'fill' in step_lower or 'type' in step_lower:
                # Find relevant field from step description
                for name, elem in elements.items():
                    if name.lower() in step_lower:
                        step_code += f'        page.fill("{elem.get("selector")}", "test_value")  # TODO: Use fixture\n'
                        break
            elif 'click' in step_lower:
                for name, elem in elements.items():
                    if name.lower() in step_lower or elem.get('text', '').lower() in step_lower:
                        step_code += f'        page.click("{elem.get("selector")}")\n'
                        break
            elif 'verify' in step_lower or 'check' in step_lower:
                step_code += f'        # TODO: Add assertion for: {step}\n'

        test_name = f"test_{journey_name.lower().replace(' ', '_')}"

        code = f'''
    def {test_name}(self, page: Page, test_credentials):
        """
        User Journey: {journey_name}

        Priority: {journey.get('priority', 'high')}
        Frequency: {journey.get('frequency', 'every release')}
        Generated: {datetime.now().isoformat()}
        """
{step_code}
'''

        return GeneratedTest(
            test_id=f"TC-{len(self._generated_tests) + 1:03d}",
            name=test_name,
            description=f"User journey: {journey_name}",
            code=code,
            priority=journey.get('priority', 'P0'),
            tags=["journey", journey_name.lower().replace(' ', '_')]
        )

    def _find_error_selector(self, elements: Dict) -> str:
        """Find error message selector from discovered elements."""
        for name, elem in elements.items():
            if 'error' in name.lower():
                return elem.get('selector', '.error-message')
        # Default fallback
        return ".error-message, .alert-error, [role='alert']"

    def _parse_generated_code(
        self,
        llm_response: str,
        request: TestGenerationRequest
    ) -> List[GeneratedTest]:
        """Parse LLM-generated code into GeneratedTest objects."""
        # Extract test functions from the response
        tests = []

        # Simple parsing - look for def test_ functions
        import re
        pattern = r'def (test_\w+)\(.*?\):\s*"""(.*?)"""'
        matches = re.findall(pattern, llm_response, re.DOTALL)

        for i, (name, docstring) in enumerate(matches):
            # Extract the full function
            func_pattern = rf'def {name}\(.*?\):.*?(?=\n    def |\nclass |\Z)'
            func_match = re.search(func_pattern, llm_response, re.DOTALL)

            if func_match:
                tests.append(GeneratedTest(
                    test_id=f"TC-{i+1:03d}",
                    name=name,
                    description=docstring.strip().split('\n')[0],
                    code=func_match.group(0),
                    priority="P1"
                ))

        return tests

    def save_tests(
        self,
        tests: List[GeneratedTest],
        output_dir: Path,
        request: TestGenerationRequest
    ) -> Path:
        """Save generated tests to a file."""

        output_dir.mkdir(parents=True, exist_ok=True)

        # Build test file
        header = f'''"""
{request.app_name} - Generated Tests
Generated by AutoGen AI QA Platform
Date: {datetime.now().isoformat()}

Discovery-based selectors: {len(request.discovered_elements)} elements
Business rules applied: {len(request.business_rules)} rules
User journeys covered: {len(request.user_journeys)} journeys

NOTE: This file was generated using AI-powered analysis of:
- Actual page elements discovered via browser automation
- Business rules from application context
- Critical user journeys requiring test coverage
"""

import pytest
from playwright.sync_api import Page, expect


@pytest.fixture
def test_credentials():
    """Test credentials - override in conftest.py for your environment."""
    return {{
        "username": "Admin",
        "password": "admin123"
    }}


class Test{request.app_name.replace(' ', '').replace('-', '')}:
    """Generated test suite for {request.app_name}."""

    BASE_URL = "{request.app_url}"
'''

        # Add all test methods
        test_code = header
        for test in tests:
            test_code += test.code + "\n"

        # Save file
        test_file = output_dir / f"test_{request.app_name.lower().replace(' ', '_')}_generated.py"
        test_file.write_text(test_code)

        logger.info(f"Saved {len(tests)} tests to {test_file}")

        return test_file


# ============================================================
# DEMONSTRATION
# ============================================================

def demonstrate_smart_generation():
    """Show the difference between template-based and smart generation."""

    print("="*70)
    print("SMART TEST GENERATION DEMONSTRATION")
    print("="*70)

    # Simulate discovery results (these would come from RealBrowserDiscoveryAgent)
    discovered_elements = {
        "username_input": {
            "type": "input",
            "selector": "input[name='username']",
            "required": True
        },
        "password_input": {
            "type": "input",
            "selector": "input[name='password']",
            "required": True
        },
        "login_button": {
            "type": "button",
            "selector": "button[type='submit']",
            "text": "Login"
        },
        "error_message": {
            "type": "text",
            "selector": "p.oxd-alert-content-text"
        }
    }

    # Business rules from context
    business_rules = [
        {
            "rule_id": "HR-001",
            "name": "Login Security",
            "description": "Users must authenticate with valid credentials",
            "applies_to": ["login", "authentication"],
            "test_implications": "Test valid/invalid login scenarios"
        }
    ]

    # User journey from context
    user_journeys = [
        {
            "name": "Admin Login Flow",
            "steps": [
                "Navigate to login page",
                "Enter username",
                "Enter password",
                "Click login button",
                "Verify dashboard displayed"
            ],
            "priority": "critical"
        }
    ]

    # Create request
    request = TestGenerationRequest(
        app_name="OrangeHRM",
        app_url="https://opensource-demo.orangehrmlive.com",
        page_url="https://opensource-demo.orangehrmlive.com/web/index.php/auth/login",
        discovered_elements=discovered_elements,
        business_rules=business_rules,
        user_journeys=user_journeys,
        tech_stack={"frontend": "Vue.js", "backend": "PHP"}
    )

    # Generate
    generator = SmartTestGenerator()
    tests = generator._generate_rule_based_tests(request)

    print(f"\n Generated {len(tests)} tests dynamically:")
    for test in tests:
        print(f"\n  📝 {test.name}")
        print(f"     Description: {test.description}")
        print(f"     Business Rules: {test.business_rule_refs}")
        print(f"     Priority: {test.priority}")

    # Show the prompt that would go to LLM
    prompt = generator._build_generation_prompt(request)
    print(f"\n LLM Prompt ({len(prompt)} chars):")
    print("-"*70)
    print(prompt[:1500] + "...\n[truncated]")

    # Save tests
    output_dir = Path("./generated_tests/smart_demo")
    test_file = generator.save_tests(tests, output_dir, request)
    print(f"\n Saved to: {test_file}")

    return tests, test_file


if __name__ == "__main__":
    demonstrate_smart_generation()
