"""
Test Valid Login
Generated by Enhanced AutoGen Test Creation Agent
"""

import pytest
import logging
from datetime import datetime
from pages.login_page import LoginPage

class TestValidLogin:
    """Test class for Valid Login"""
    
    def test_valid_login(self, browser_setup):
        """
        Test: Valid Login
        Description: Test login with valid credentials
        """
        page, browser, context = browser_setup
        
        try:
            # Initialize page object
            page_obj = LoginPage(page)
            
            # Navigate to application
            page.goto("https://demo.testfire.net")
            page.wait_for_load_state("networkidle")
            
            # Execute test steps with discovered selectors
            # Step 1: Navigate to login page
            # Navigate using page object
            page_obj.navigate()
            # Step 2: Enter valid username
            # Enter username using page object
            page_obj.fill_username("Admin")
            page.wait_for_timeout(200)
            # Step 3: Enter valid password
            # Enter password using page object
            page_obj.fill_password("admin123")
            page.wait_for_timeout(200)
            # Step 4: Click login button
            # Click login button using page object
            page_obj.click_login()
            page.wait_for_timeout(500)
            # Step 5: Verify successful login
            # Verification step 5
            # Wait for expected element to be visible
            page.wait_for_selector("body", timeout=5000)
            
            # Assert the step was successful
            assert page.url is not None, "Page should be loaded"

            # Final verification
            page.wait_for_timeout(1000)  # Allow UI to settle
            
            logging.info(f"Test valid_login completed successfully")
            
        except Exception as e:
            logging.error(f"Test valid_login failed: {str(e)}")
            raise
