"""
Enhanced API endpoints for test creation and management
"""
from fastapi import APIRouter, HTTPException, BackgroundTasks
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
import asyncio
import json
from datetime import datetime

from database import Application, TestSuite, AgentJob, AgentActivity

router = APIRouter()

class CreateTestRequest(BaseModel):
    url: str
    name: str
    type: str
    key_features: str
    user_flows: str

class TestCreationResponse(BaseModel):
    success: bool
    job_id: int
    application_id: int
    message: str

class AgentProgressUpdate(BaseModel):
    job_id: int
    agent_name: str
    status: str
    progress: int
    message: str

# Simulated agent workflow
AGENT_WORKFLOW = [
    {"name": "Discovery Agent", "duration": 3, "description": "Analyzing application structure"},
    {"name": "Test Generation Agent", "duration": 5, "description": "Generating test scenarios"},
    {"name": "Code Generation Agent", "duration": 4, "description": "Creating test automation code"},
    {"name": "Validation Agent", "duration": 2, "description": "Validating generated tests"}
]

async def simulate_agent_workflow(job_id: int, application_id: int):
    """Simulate the agent workflow with real-time updates"""
    try:
        total_duration = sum(agent["duration"] for agent in AGENT_WORKFLOW)
        current_progress = 0
        
        for i, agent in enumerate(AGENT_WORKFLOW):
            # Update job with current agent
            AgentJob.update_progress(job_id, agent["name"], current_progress, "running")
            
            # Create agent activity
            AgentActivity.create(
                job_id=job_id,
                agent_name=agent["name"],
                activity_type="processing",
                status="running",
                progress=current_progress,
                message=agent["description"]
            )
            
            # Simulate agent work with incremental progress updates
            steps = agent["duration"]
            for step in range(steps):
                await asyncio.sleep(1)  # Simulate work
                step_progress = current_progress + ((step + 1) / steps) * (agent["duration"] / total_duration * 100)
                
                # Update progress
                AgentJob.update_progress(job_id, agent["name"], int(step_progress), "running")
                
                # Create progress activity
                AgentActivity.create(
                    job_id=job_id,
                    agent_name=agent["name"],
                    activity_type="progress",
                    status="running",
                    progress=int(step_progress),
                    message=f"{agent['description']} - Step {step + 1}/{steps}"
                )
            
            # Mark agent as completed
            current_progress += (agent["duration"] / total_duration * 100)
            AgentActivity.create(
                job_id=job_id,
                agent_name=agent["name"],
                activity_type="completed",
                status="completed",
                progress=int(current_progress),
                message=f"{agent['name']} completed successfully"
            )
        
        # Create test suite after all agents complete
        test_suite_id = TestSuite.create(
            application_id=application_id,
            name=f"AI Generated Test Suite",
            description="Comprehensive test suite generated by AI agents",
            test_type="functional"
        )
        
        # Mark job as completed
        AgentJob.complete_job(job_id, "completed")
        
        # Final completion activity
        AgentActivity.create(
            job_id=job_id,
            agent_name="System",
            activity_type="completed",
            status="completed",
            progress=100,
            message=f"Test suite created successfully (ID: {test_suite_id})",
            details={"test_suite_id": test_suite_id}
        )
        
    except Exception as e:
        # Mark job as failed
        AgentJob.update_progress(job_id, "System", 0, "failed")
        AgentActivity.create(
            job_id=job_id,
            agent_name="System",
            activity_type="error",
            status="failed",
            progress=0,
            message=f"Job failed: {str(e)}"
        )

@router.post("/create-test", response_model=TestCreationResponse)
async def create_test(request: CreateTestRequest, background_tasks: BackgroundTasks):
    """Create a new test with AI agent processing"""
    try:
        # Create application record
        application_id = Application.create(
            user_id=1,  # Default user for demo
            name=request.name,
            url=request.url,
            app_type=request.type,
            description=f"Application for {request.type} testing",
            key_features=request.key_features,
            user_flows=request.user_flows
        )
        
        # Create agent job
        job_id = AgentJob.create(
            application_id=application_id,
            job_type="test_creation"
        )
        
        # Start agent workflow in background
        background_tasks.add_task(simulate_agent_workflow, job_id, application_id)
        
        return TestCreationResponse(
            success=True,
            job_id=job_id,
            application_id=application_id,
            message="Test creation started successfully"
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create test: {str(e)}")

@router.get("/test-suites")
async def get_test_suites():
    """Get all test suites"""
    try:
        test_suites = TestSuite.get_all()
        return {
            "success": True,
            "test_suites": test_suites
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch test suites: {str(e)}")

@router.get("/agent-job/{job_id}")
async def get_agent_job(job_id: int):
    """Get agent job status and progress"""
    try:
        job = AgentJob.get_by_id(job_id)
        if not job:
            raise HTTPException(status_code=404, detail="Job not found")
        
        activities = AgentActivity.get_by_job(job_id)
        
        return {
            "success": True,
            "job": job,
            "activities": activities
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch job: {str(e)}")

@router.get("/agent-activities")
async def get_agent_activities(limit: int = 10):
    """Get recent agent activities"""
    try:
        activities = AgentActivity.get_recent(limit)
        return {
            "success": True,
            "activities": activities
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch activities: {str(e)}")

@router.get("/applications")
async def get_applications():
    """Get all applications"""
    try:
        applications = Application.get_by_user(1)  # Default user for demo
        return {
            "success": True,
            "applications": applications
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch applications: {str(e)}")

@router.post("/test-suite/{suite_id}/run")
async def run_test_suite(suite_id: int):
    """Run a test suite"""
    try:
        # Update test suite status to running
        TestSuite.update_status(suite_id, "running")
        
        # In a real implementation, this would trigger actual test execution
        # For now, we'll simulate it
        
        return {
            "success": True,
            "message": f"Test suite {suite_id} execution started"
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to run test suite: {str(e)}")

@router.delete("/test-suite/{suite_id}")
async def delete_test_suite(suite_id: int):
    """Delete a test suite"""
    try:
        # In a real implementation, this would delete the test suite
        # For now, we'll just return success
        
        return {
            "success": True,
            "message": f"Test suite {suite_id} deleted successfully"
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete test suite: {str(e)}")
